apiVersion: 1

datasources:
  - name: WeatherPostgres
    uid: weather-postgres
    type: postgres
    url: postgres:5432
    database: weather_db
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
    editable: true
